// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

  docs: [{type: 'autogenerated', dirName: 'documentation'}],
  visualArrays: [{type: 'autogenerated', dirName: 'visual-arrays'}],
  bienDebuter: [{type: 'autogenerated', dirName: 'bien-debuter'}],
  examens: [{type: 'autogenerated', dirName: 'examens'}]

};

module.exports = sidebars;
