// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

  docs: [{type: 'autogenerated', dirName: '01-documentation'}],
  visualArrays: [{type: 'autogenerated', dirName: '02-visual-arrays'}],
  bienDebuter: [{type: 'autogenerated', dirName: '03-bien-debuter'}],
  examens: [{type: 'autogenerated', dirName: '04-examens'}]

};

module.exports = sidebars;
