name: Tester le build

on:
  pull_request:
    branches:
      - main

jobs:
  test-build:
    name: Tester le build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Installer les dépendances
        run: npm ci
      - name: Build du site
        run: npm run build
